services:
  node:
    image: node
    ports:
      - 3006:3006
    working_dir: /var/drip-package-frontend/
    volumes:
      - ./static:/var/drip-package-frontend/static
      - ./readme/:/Users/eric/OpenSource/drip-file/docker/drip-package-frontend/readme/
      - ./dist:/var/drip-package-frontend/dist/
      - ./node_modules/:/var/drip-package-frontend/node_modules/
      - ./asset/:/var/drip-package-frontend/asset/
    command: node ./dist/index.js -p 3006 -r ./readme/
